export const mock = {
  name: "Fernando",
  lastname: "Brum",
  cpf: "12345678912",
  email: "teste@teste.com",
  phone: "5544998525",
  password: "senha teste",
  confirmPassword: "senha teste",
  zipcode: "",
  street: "",
  number: "",
  complement: "",
  neighborhood: "",
  city: "",
  state: "",
  country: "",
};

export const DEFAULT_USER_INFO = {
  name: "",
  lastname: "",
  cpf: "",
  email: "",
  phone: "",
  password: "",
  confirmPassword: "",
  zipcode: "",
  street: "",
  number: "",
  complement: "",
  neighborhood: "",
  city: "",
  state: "",
  country: "",
};
